### ISSUE TITLE
Downloads fail when behind a proxy

### ISSUE THREAD

**Issue by wtbarnes** [sunpy/sunpy#3336]
File downloads (e.g. sample data, anything via Fido) with parfive fail when behind a proxy. In parfive, this is easily solved by simply passing the keyword `proxy='.<my-proxy-url>'` to the `enqueue_file` method.

The question is then how should this option be propagated through to that method? Presumably this could just be set in the config file and then passed as a kwarg anytime `enqueue_file` is called.

**Comment by dmackenz13** [comment]
Hello, sir.
I spoke with "cadair" on IM abut this issue.

I have addressed this (for my site at least), with the following in parfive's site-packages/parfive/downloader.py 

```
154         if ((str(scheme + '_PROXY').upper() in os.environ) and
155            ('proxy' not in kwargs)):
156             kwargs['proxy'] = os.environ[(str(scheme + '_PROXY').upper())]
```

No idea if that's the best way to handle this, but it's working for us.

**Comment by wtbarnes** [comment]
Thanks @dmackenz13. Coincidentally, this was just pointed out to me by someone else as well. I actually think you don't even need to do this in parfive. You just need to set this environment variable appropriately (e.g. in that Python session or in a `.bashrc`). This is probably the preferred solution compared to making a change in parfive.

**Comment by dmackenz13** [comment]
@wtbarnes , I don't understand at all.  I absolutely have this variable set in my ~/.bashrc (If I didn't, the os.environ call in my code snippet wouldn't return anything).

The problem is that Fido isn't sending it through to parfive.  On Riot IM, Stuart Mumford suggested that it be handled in parfive directly so that sunpy contributors didn't have to remember to use it.  Hence, my snippet above which is now allowing me to collect HMI Vector magnetograms.

It's immaterial to me whether it's handled by Fido or parfive, but I am hoping *some* method of honoring the variable can make it into a released version.

**Comment by pkj-m** [comment]
Hi @dmackenz13 I have recently started working on sunpy and ran into a similar problem of not being able to download data through Fido due to proxy. I did what you suggested by modifying parfive's code to consider the proxy however it still fails to connect with the address where the data is being hosted. On executing the `downloading_hmi.py` example, I get the following error:

```
Results from 1 Provider:

1 Results from the JSOCClient:
         T_REC            CROTA2 
         str23           float64 
----------------------- ---------
2014.11.20_00:00:00_TAI 180.01355


Export request pending. [id="JSOC_20200201_242", status=2]
Waiting for 0 seconds...
1 URLs found for download. Full request totalling 15MB
Files Downloaded:   0%|                                                               | 0/1 [02:10<?, ?file/s]
[]
Errors:
(error(filepath_partial=<function Downloader.enqueue_file.<locals>.filepath at 0x7fd307846b00>, url='http://jsoc.stanford.edu/SUM66/D1255884753/S00000/hmi.m_720s.20141120_000000_TAI.1.magnetogram.fits', exception=ClientConnectorError(ConnectionKey(host='jsoc.stanford.edu', port=80, is_ssl=False, ssl=None, proxy=None, proxy_auth=None, proxy_headers_hash=None), TimeoutError(110, "Connect call failed ('171.64.103.244', 80)"))))
Traceback (most recent call last):
  File "downloading_hmi.py", line 49, in <module>
    hmi_map = sunpy.map.Map(downloaded_file[0])
  File "/home/pankaj/anaconda3/envs/sunpy-dev/lib/python3.7/collections/__init__.py", line 1098, in __getitem__
    return self.data[i]
IndexError: list index out of range
```

Is there something I am missing here that is causing this error?

**Comment by Raahul-Singh** [comment]
@Cadair shall we close this now?

**Comment by Cadair** [comment]
@pkj-m That error looks like it hasn't used the proxy. Parfive 1.1rc2 supports the `HTTP_PROXY` and `HTTPS_PROXY` environment variables. If you could test that it would be great.

**Comment by abhijeetmanhas** [comment]
@Cadair @nabobalis can this be closed now after the parfive PR ?

**Comment by nabobalis** [comment]
Is the parfive PR enough to fix this issue?

**Comment by Cadair** [comment]
We should probably document it.

**Comment by wtbarnes** [comment]
I'm going to close this in light of the new changes in 2.0 and parfive 1.1. See https://docs.sunpy.org/en/stable/whatsnew/2.0.html#download-behind-proxies
